apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-pvc-{{ .Values.appEnvrionment }}
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
