apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.images.drupal.name }}-config-{{ .Values.appEnvironment }}"
data:
    MARIADB_USER: "{{ .Values.secrets.database.username }}"
    MARIADB_PASSWORD: "{{ .Values.secrets.database.password }}"
    MARIADB_DATABASE: "{{ .Values.secrets.database.database }}"
    MARIADB_HOST: "{{ .Values.secrets.database.host }}"
    MARIADB_PORT: "{{ .Values.secrets.database.port }}"
    QUANT_SMTP_HOST: "{{ .Values.secrets.smtp.host }}"
    QUANT_SMTP_PORT: "{{ .Values.secrets.smtp.port }}"
    QUANT_SMTP_USERNAME: "{{ .Values.secrets.smtp.username }}"
    QUANT_SMTP_PASSWORD: "{{ .Values.secrets.smtp.password }}"
    QUANT_SMTP_FROM: "{{ .Values.secrets.smtp.from }}"
    QUANT_SMTP_FROM_NAME: "{{ .Values.secrets.smtp.from_name }}"
    REDIS_HOST: "{{ .Values.secrets.redis.host }}"

    APACHE_RUN_USER: nobody
    QUANT_PRODUCTION_ENVIRONMENT: "{{ .Values.productionBranch | default "main" }}"
    QUANT_ENVIRONMENT_BRANCH: "{{ .Values.appEnvironment }}"
    QUANT_ENVIRONMENT_TYPE: "{{ include "quant.environmentType" . }}"
    QUANT_PROJECT_UUID: "{{ .Values.secrets.quant.project_uuid | b64dec }}"
