{{- if eq .Values.productionBranch .Values.appEnvironment }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-config
  namespace: default
data:
  000-routing.conf: |
    location /sites/default/files {
      proxy_pass http://{{ .Values.images.drupal.name }}-$quant_cloud_environment.$fdqn;
    }

    location /themes {
      proxy_pass http://{{ .Values.images.drupal.name }}-$quant_cloud_environment.$fdqn;
    }
 {{- end }}