{{- if eq .Values.productionBranch .Values.appEnvironment }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: location-optimizer
  namespace: default
data:
  strategy:
  {{- if eq .Values.region "us" }}
  |
    {
      "strategy":"SolverServiceV1",
      "params": {
        "policy": "static",
        "mustInclude": [
            {"locationcode":"lax","provider":"lumen"}
        ],
        "chooseFrom": ["well-known-egress-ips"],
        "minimumLocations": 1,
        "maximumLocations": 1
      }
    }
  {{- else if eq .Values.region "au" }}
    {
      "strategy":"SolverServiceV1",
      "params": {
        "policy": "static",
        "mustInclude": [
            {"locationcode":"bne","provider":"rackcorp"}
        ],
        "minimumLocations": 1,
        "maximumLocations": 1
      }
    }
  {{- else }}
  |
    {
      "strategy":"SolverServiceV1",
      "params": {
        "policy": "dynamic",
        "chooseFrom": ["well-known-egress-ips"]
      }
    }
  {{- end }}
 {{- end }}
