apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.images.nextjs.name }}-config-{{ .Values.appEnvironment }}
data:
    NEXT_PUBLIC_DRUPAL_BASE_URL: {{ .Values.images.nextjs.config.drupal_base | default "http://localhost" }}
    NEXT_PUBLIC_IMAGE_DOMAIN: "" # Relative images on Quant Cloud.
    DRUPAL_PREVIEW_SECRET: {{ .Values.secrets.drupal.preview_secret | default "secret" }}
    DRUPAL_REVALIDATE_SECRET: {{ .Values.secrets.drupal.revalidate_secret | default "secret" }}