apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    timestamp: {{ now | quote }}
  name: "{{ include "quant.name" . }}-{{ .Values.appEnvironment }}"
  labels:
    app: "{{ include "quant.name" . }}-{{ .Values.appEnvironment }}"
    version: {{ .Values.appVersion }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "quant.selectorLabels" . | nindent 6 }}
      app: "{{ include "quant.name" . }}-{{ .Values.appEnvironment }}"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "quant.selectorLabels" . | nindent 8 }}
        app: "{{ include "quant.name" . }}-{{ .Values.appEnvironment }}"
        version: {{ .Values.appVersion }}
    spec:
      imagePullSecrets:
        - name: quant-cloud
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: authorized-keys
          configMap:
            name: authorized-keys-{{ .Values.appEnvironment }}
            defaultMode: 384
        - name: {{ .Values.images.drupal.name }}-data
          persistentVolumeClaim:
            claimName: "{{ .Values.images.drupal.name }}-pvc-{{ .Values.appEnvironment }}"
        - name: {{ .Values.images.nextjs.name }}-data
          persistentVolumeClaim:
            claimName: "{{ .Values.images.nextjs.name }}-pvc-{{ .Values.appEnvironment }}"
        {{- if .Values.images.redis.enabled }}
        - name: redis-data
          persistentVolumeClaim:
            claimName: "redis-pvc-{{ .Values.appEnvironment }}"
        {{- end }}
      containers:
        ### BEGIN DRUPAL CONTAINER
        - name: "{{ .Values.images.drupal.name }}-{{ .Values.appEnvironment }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.drupal.repository }}:{{ .Values.images.drupal.tag }}"
          imagePullPolicy: {{ .Values.images.drupal.pullPolicy | default "Always" }}
          lifecycle:
            postStart:
              exec:
                command:
                  - backend-init
                  - verify
                  - http://localhost/jsonapi
                  - --delay=5
                  - --retries=30
          ports:
            - name: {{ .Values.images.drupal.name }}
              containerPort: {{ .Values.images.drupal.port }}
              protocol: TCP
            - name: {{ .Values.images.drupal.sshname }}
              containerPort: {{ .Values.images.drupal.sshport }}
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.images.drupal.port }}
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.images.drupal.port }}
            timeoutSeconds: 1
          envFrom:
            - configMapRef:
                name: "{{ .Values.images.drupal.name }}-config-{{ .Values.appEnvironment }}"
          volumeMounts:
            - name: authorized-keys
              mountPath: /root/.ssh/authorized_keys
              subPath: authorized_keys
            - name: {{ .Values.images.drupal.name }}-data
              mountPath: /opt/drupal/web/sites/default/files
          resources:
            {{- if eq .Values.productionBranch .Values.appEnvironment }}
            {{- toYaml .Values.images.drupal.resources | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.images.drupal.devresources | nindent 12 }}
            {{- end }}
        ### END DRUPAL CONTAINER
        ### BEGIN NEXTJS CONTAINER
        - name: {{ .Values.images.nextjs.name }}-{{ .Values.appEnvironment }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.nextjs.repository }}:{{ .Values.images.nextjs.tag }}"
          imagePullPolicy: {{ .Values.images.nextjs.pullPolicy | default "Always" }}
          ports:
            - name: {{ .Values.images.nextjs.name }}
              containerPort: {{ .Values.images.nextjs.port }}
              protocol: TCP
          startupProbe:
            failureThreshold: 50
            periodSeconds: 10
            httpGet:
              path: /.well-known/startup
              port: {{ .Values.images.nextjs.port }}
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              path: /.well-known/ready
              port: {{ .Values.images.nextjs.port }}
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 5
            successThreshold: 1
            httpGet:
              path: /.well-known/liveness
              port: {{ .Values.images.nextjs.port }}
          envFrom:
            - configMapRef:
                name: "{{ .Values.images.drupal.name }}-config-{{ .Values.appEnvironment }}"
            - configMapRef:
                name: "{{ .Values.images.nextjs.name }}-config-{{ .Values.appEnvironment }}"
          volumeMounts:
            - name: {{ .Values.images.nextjs.name }}-data
              mountPath: /app/.next
          resources:
            {{- if eq .Values.productionBranch .Values.appEnvironment }}
            {{- toYaml .Values.images.nextjs.resources | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.images.nextjs.devresources | nindent 12 }}
            {{- end }}
        ### END NEXTJS CONTAINER
        ### BEGIN REDIS CONTAINER
        {{- if .Values.images.redis.enabled }}
        - name: {{ .Values.images.redis.name }}-{{ .Values.appEnvironment }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.redis.repository }}:{{ .Values.images.redis.tag }}"
          command:
            - redis-server
            - --save 60 1
            - --loglevel warning
            - --maxmemory-policy {{ .Values.images.redis.cachePolicy | default "volatile-lru" }}
            {{- if eq .Values.productionBranch .Values.appEnvironment }}
            - --maxmemory {{ .Values.images.redis.maxMemory | default "419430400" }}
            {{- else }}
            - --maxmemory {{ .Values.images.redis.maxMemoryDev | default "209715200" }}
            {{- end }}
          imagePullPolicy: {{ .Values.images.redis.pullPolicy | default "Always" }}
          ports:
            - name: {{ .Values.images.redis.name }}
              containerPort: {{ .Values.images.redis.port }}
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.images.redis.port }}
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.images.redis.port }}
          envFrom:
            - configMapRef:
                name: "{{ .Values.images.drupal.name }}-config-{{ .Values.appEnvironment }}"
          {{- if eq .Values.productionBranch .Values.appEnvironment }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
          {{- end }}
          resources:
            {{- if eq .Values.productionBranch .Values.appEnvironment }}
            {{- toYaml .Values.images.redis.resources | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.images.redis.devresources | nindent 12 }}
            {{- end }}
        {{- end }}
        ### END REDIS CONTAINER
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}