{{- if eq .Values.productionBranch .Values.appEnvironment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: quant-ingress
  labels:
    app: quant-ingress
spec:
  selector:
    matchLabels:
      app: quant-ingress
  template:
    metadata:
      labels:
        app: quant-ingress
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: ingress-config
          configMap:
            name: ingress-config
      containers:
        ### BEGIN INGRESS CONTAINER
        - name: ingress
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: registry.quant.cloud/quant-public/ingress:1.0.16
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: ingress-config
              mountPath: /etc/nginx/conf.d/all/000-routing.conf
              subPath: 000-routing.conf
          resources:
            requests:
              memory: ".25Gi"
              cpu: "200m"
            limits:
              memory: ".25Gi"
              cpu: "200m"
        ### END INGRESS CONTAINER
 {{- end }}