{{- if ! .Values.secrets.s3fs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.images.drupal.name }}-pvc-{{ .Values.appEnvironment }}"
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      {{- if eq .Values.productionBranch .Values.appEnvironment }}
      storage: {{ .Values.images.drupal.storage }}
      {{- else }}
      storage: {{ .Values.images.drupal.devstorage }}
      {{- end }}
{{- end }}