{{- if .Values.images.redis.enabled }}
{{- if eq .Values.productionBranch .Values.appEnvironment }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "redis-pvc-{{ .Values.appEnvironment }}"
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
{{- end }}
{{- end }}