{{- if eq .Values.productionBranch .Values.appEnvironment }}
apiVersion: v1
kind: Service
metadata:
  name: ingress-upstream
  namespace: default
  labels:
    app: ingress-upstream
spec:
    ports:
    - name: 80-80
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
        app: "{{ .Values.images.drupal.name }}-{{ .Values.appEnvironment }}"
    sessionAffinity: None
    type: ClusterIP
status:
    loadBalancer: {}
{{- end }}