apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quant-waf.fullname" . }}-app-config
data:
  403.html: |-
{{ .Values.quant.errorPages.blocked | nindent 4 }}
  429.html: |-
{{ .Values.quant.errorPages.threshold | nindent 4 }}
  config.json: {{ include "quant-waf.config" . | trim | quote }}
  quant.config.json: {{ include "quant-waf.quantConfig" . | trim | quote }}
  server.conf: |
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header Connection '';
    proxy_pass_header Server;

    resolver local=on 8.8.8.8 ipv6=off;
    resolver_timeout 5s;

    location / {
      rewrite_by_lua_block {
        local quant = require('quant/entrypoint')
        quant.rewrite()
      }
      proxy_pass http://next_hop_upstream;
    }

    location @wafapi {
      proxy_pass http://127.0.0.1:888;
    }

