apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quant-waf.fullname" . }}
  labels:
    {{- include "quant-waf.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      {{- include "quant-waf.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.waf.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "quant-waf.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.waf.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "registry.quant.cloud/quant-public/quant-waf:{{ .Values.waf.version | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.waf.pullPolicy }}
          volumeMounts:
            - mountPath: /opt/proxy_config
              name: {{ include "quant-waf.fullname" . }}-config-mount
          envFrom:
            - configMapRef:
                name: {{ include "quant-waf.fullname" . }}-config-map
          env:
            - name: QUANT_LICENSE
              valueFrom:
                secretKeyRef:
                  name: {{ include "quant-waf.fullname" . }}-license
                  key: licenseKey
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: http
          resources:
            {{- toYaml .Values.waf.resources | nindent 12 }}
      {{- with .Values.waf.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.waf.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.waf.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "quant-waf.fullname" . }}-config-mount
          configMap:
            name: {{ include "quant-waf.fullname" . }}-app-config


