# This is a YAML-formatted file.
# Provides default variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""
productionBranch: main

images:
  pullPolicy: Always
  app:
    name: node-express
    branch: main
    repository: registry.quant.cloud/org/repo
    tag: edge
    port: 3000
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 200m
        memory: 200Mi
    devresources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  name: node-express
  type: ClusterIP
  port: 3000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.1.0"

# Secrets
# Manage app secrets with kubernetes rather than committing
# in the codebase itself.
secrets:
  registry:
    user:
    token:
    registry: registry.quant.cloud