apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "drupal-pvc-{{ .Values.appEnvironment }}"
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      {{- if eq .Values.productionBranch .Values.images.app.tag }}
      storage: {{ .Values.images.drupal.storage }}
      {{- else }}
      storage: {{ .Values.images.drupal.devstorage }}
      {{- end }}
