{{- if eq .Values.productionBranch .Values.images.app.tag }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: location-optimizer
  namespace: default
data:
  strategy:
  {{- if eq .Values.region "us" }}
  |
    {
      "strategy":"SolverServiceV1",
      "params": {
        "policy": "static",
        "mustInclude": [
            {"locationcode":"sea", "provider": "lumen"}
        ]
        "minimumLocations": 1,
        "maximumLocations": 1
      }
    }
  {{- else }}
  |
    {
      "strategy":"SolverServiceV1",
      "params": {
        "policy": "dynamic",
        "chooseFrom": ["well-known-egress-ips"]
      }
    }
  {{- end }}
 {{- end }}
