{{- if eq .Values.productionBranch .Values.images.app.tag }}
apiVersion: v1
kind: Secret
metadata:
  name: quant-cloud
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "quant.imagePullSecretValue" . }}
{{- end }}