{{- if .Values.images.redis.enabled }}
{{- if eq .Values.productionBranch .Values.images.app.tag }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
{{- end }}
{{- end }}