{{- if eq .Values.productionBranch .Values.images.app.tag }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: app-default
  namespace: default
  labels:
    app: app-default
spec:
    ports:
    - name: 80-{{ .Values.images.app.port }}
      port: 80
      protocol: TCP
      targetPort: {{ .Values.images.app.port }}
    selector:
        app: "{{ .Values.images.app.name }}-{{ .Values.productionBranch }}"
    sessionAffinity: None
    type: ClusterIP
status:
    loadBalancer: {}
 {{- end }}